package com.jetherrodrigues.producer.config.queue;

public final class QueueDefinition {
    public static String CONSOLIDATION_HA_QUEUE = "CONSOLIDATION_HA_QUEUE";
    public static String CONSOLIDATION_HA_QUEUE_BINDING_KEY = "CONSOLIDATION_HA_QUEUE_BINDING_KEY";
    public static String CONSOLIDATION_HA_QUEUE_DLQ = "CONSOLIDATION_HA_QUEUE_DLQ";
    public static String CONSOLIDATION_HA_QUEUE_DLQ_BINDING_KEY = "CONSOLIDATION_HA_QUEUE_DLQ_BINDING_KEY";

    public static String BOLETIM_HA_QUEUE = "BOLETIM_HA_QUEUE";
    public static String BOLETIM_HA_QUEUE_BINDING_KEY = "BOLETIM_HA_QUEUE_BINDING_KEY";
    public static String BOLETIM_HA_QUEUE_DLQ = "BOLETIM_HA_QUEUE_DLQ";
    public static String BOLETIM_HA_QUEUE_DLQ_BINDING_KEY = "BOLETIM_HA_QUEUE_DLQ_BINDING_KEY";

    public static String MET_WARNING_HA = "MET_WARNING_HA";
    public static String MET_WARNING_HA_BINDING_KEY = "MET_WARNING_HA_BINDING_KEY";
    public static String MET_WARNING_HA_DLQ = "MET_WARNING_HA_DLQ";
    public static String MET_WARNING_HA_DLQ_BINDING_KEY = "MET_WARNING_HA_DLQ_BINDING_KEY";

    public static String INFORMATIVE_HA_QUEUE = "INFORMATIVE_HA_QUEUE";
    public static String INFORMATIVE_HA_QUEUE_BINDING_KEY = "INFORMATIVE_HA_QUEUE_BINDING_KEY";
    public static String INFORMATIVE_HA_QUEUE_DLQ = "INFORMATIVE_HA_QUEUE_DLQ";
    public static String INFORMATIVE_HA_QUEUE_DLQ_BINDING_KEY = "INFORMATIVE_HA_QUEUE_DLQ_BINDING_KEY";

    public static String PRODUCT_FILE_QUEUE = "PRODUCT_FILE_QUEUE";
    public static String PRODUCT_FILE_QUEUE_BINDING_KEY = "PRODUCT_FILE_QUEUE_BINDING_KEY";
    public static String PRODUCT_FILE_QUEUE_DLQ = "PRODUCT_FILE_QUEUE_DLQ";
    public static String PRODUCT_FILE_QUEUE_DLQ_BINDING_KEY = "PRODUCT_FILE_QUEUE_DLQ_BINDING_KEY";
}
